name:                golfing
version:             0.1.0
github:              "ahilke/golfing"
license:             MIT
author:              "Arno Hilke"
maintainer:          "arno.hilke@tum.de"
copyright:           "2019 Arno Hilke"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/golfing#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  divisor-exe:
    main:                Main.hs
    source-dirs:         src/Divisor
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Divisor.Main
    dependencies:
    - golfing
